# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: DonaLora
title_separator: "|"
subtitle: Where ideas are born
email: info@donalora.com
description: >-
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.donalora.com"
twitter_username:
github_username: donalora
repository: donalora/donalora.github.io

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-117860308-1"
    anonymize_ip: false
google_site_verification: "TNCfmN6ePVb12cLcKYnJblctOLA_14BiBG8V-ey45Ms"
minimal_mistakes_skin: air
search: true
timezone: Europe/London
author:
  name: "Laura"
#  avatar: ""
#  bio: ""
  location: "UK"
#  links:
#    - label: "Thread Of Fashion"
#      icon: "/assets/img/donalora-logo.png"
#      url: "https://www.thread-of-fashion.com"
logo: /assets/img/donalora-logo.png
breadcrumbs: true
footer:
  links:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "http://www.facebook.com/DonaLoraShop"
    - label: "Etsy"
      icon: "fab fa-fw fa-etsy"
      url: "https://www.etsy.com/uk/shop/ThreadOfFashionByDL"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/donaloraknitting_official/"
    - label: "Pinterest"
      icon: "fab fa-fw fa-pinterest"
      url: "https://www.pinterest.co.uk/donaloraknitting_official/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
      read_time: true
      share: true

# Build settings
markdown: kramdown
#theme: minima
remote_theme: "mmistakes/minimal-mistakes@4.19.1"
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
